# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Xin Lan | Water Resources & Machine Learning"
title_separator          : "-"
name                     : &name "Xin Lan"
description              : &description "PhD Candidate in water resources and machine learning"
url                      : https://xinlan-science.github.io
baseurl                  : ""
repository               : "xinlan-science/xinlan-science.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Xin Lan"
  pronouns         : "He/Him/His"  
  bio              : "PhD candidate at Michigan State University"
  location         : "East Lansing, MI"
  employer         : "Michigan State University"
  uri              : "https://geo.msu.edu/directory/lan-xin.html"
  email            : "lanxin1@msu.edu" 
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=hDHQtHAAAAAJ&view_op=list_works&sortby=pubdate"
  orcid            : "https://orcid.org/0000-0002-0607-2270"
  researchgate     : "https://www.researchgate.net/profile/Xin-Lan-20"
  linkedin         : "/xin-lan-585912184/"
  github           : "xinlan-science"
  twitter          : "ShaneResearch"

# Publication Category
publication_category:
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
  preprints:
    title: 'Preprints'

# Site Settings
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  awards:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  - scope:
      path: ""
      type: awards
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: news
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
